# Generated by Django 4.0.2 on 2023-03-04 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_comment_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='date',
        ),
    ]
